db:
  image: mysql:5.6
  container_name: db
  environment:
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

memcache:
  image: memcached:1.4.24
  container_name: memcache

dummy-webapp:
  # Uncomment this line to use the official dummy-webapp base image
  image: dummy-webapp:v1

  # Uncomment the next two lines to build from a local configuration repo
  #build: ../configuration
  #dockerfile: docker/build/dummy-webapp/Dockerfile

  container_name: dummy-webapp
  volumes:
    - .:/edx/app/dummy-webapp/dummy-webapp
  command: /edx/app/dummy-webapp/devstack.sh start
  ports:
    - "8000:8000" # TODO: change this to your port
